In [1]:
import torch
from IPython import display
from d2l import torch as d2l

In [2]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [3]:
# 初始化模型参数
num_inputs = 784  # 28*28
num_outputs = 10

W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

In [4]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)  # 假设X是（50，10）保留列的维度，结果仍然是二维
    return X_exp / partition

In [5]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X, X_prob, X_prob.sum(axis=1, keepdim=True) 

(tensor([[-0.0741, -0.4430,  0.4140,  0.7913, -0.7252],
         [ 0.1637, -0.2511,  0.4324, -0.1225,  0.7517]]),
 tensor([[0.1608, 0.1112, 0.2620, 0.3821, 0.0839],
         [0.1811, 0.1196, 0.2370, 0.1361, 0.3261]]),
 tensor([[1.],
         [1.]]))

In [ ]:
# 定义模型
def net(X):
    return softmax(torch.matmul(X.reshape(-1, W.shape[0]), W) + b)

In [24]:
# 高级索引
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.9, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]  # 选择y_hat[0][0] and y_hat[1][2]

tensor([0.9000, 0.5000])

In [ ]:
# 定义损失函数
def cross_entropy(y_hat, y):
    return -torch.log(y_hat[range(len(y_hat)), y])

cross_entropy(y_hat, y)

tensor([0.0202, 0.6931])